"""add active_record_id 

Revision ID: 102292082735
Revises: edb862b69f4f
Create Date: 2026-05-11 20:04:32.764853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '102292082735'
down_revision: Union[str, Sequence[str], None] = 'edb862b69f4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bazi_profile', sa.Column('active_record_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key('fk_bazi_profile_active_record', 'bazi_profile', 'user_record', ['active_record_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_bazi_profile_active_record', 'bazi_profile', type_='foreignkey')
    op.drop_column('bazi_profile', 'active_record_id')
    # ### end Alembic commands ###
